#define BG_HOME_COLOR 					11
#define BG_COLOR 						11
#define BG_ADD  						0
#define TEXT_TITLE  					0
#define BG_EDITTEXT_COLOR				15
#define TEXT_TITLE_COLOR				12
#define TEXT_COLOR 						9
#define BORDER_COLOR 					6
#define TEXT_EDIITEXT_TITLE_COLOR 		0
#define TEXT_EDIITEXT_HINT_COLOR 		7
#define TEXT_EDITTEXT_COLOR				0
#define BG_BUTTON_DEFAULT 				7
#define BG_BUTTON_SELECT 				12
#define TEXT_BUTTON_SELECT 				15
#define TEXT_BUTTON_DEFAULT				0
#define LINE							8
#define TIPS 							4

#define MAX_SIZE_DAUSACH 				300
#define MAX_DOC_GIA 					200
#define QUEUE_CAPACITY 					200
#define START_ID_DG						1e4
#define END_ID_DG 						1e5

const int ENTER = 13;
const int BACKSPACE = 8;// lui lai va xoa
const int SPACE = 32;

enum Window {THEM_DAU_SACH, HIEU_CHINH_DAU_SACH, DANH_MUC_SACH, THEM_DOC_GIA, HIEU_CHINH_DOC_GIA, XOA_DOC_GIA, MUON_SACH, TRA_SACH, TOP_TEN , HIEU_CHINH_DOC_GIA_DONE, HIEU_CHINH_DAU_SACH_DONE, XOA_DAU_SACH_DONE};
enum SubWindow {XOA_DAU_SACH,NHAP_SACH, THEM_SACH, HIEU_CHINH_SACH, XAC_NHAN_TRA_SACH, XAC_NHAN_LAM_MAT_SACH};
enum ScanType{ ONLY_NUMBER, ONLY_NUMBER_GREATER_0, LIMIT_CHARACTER, ONLY_TEXT, SPACE_TEXT, TEXT_NUMBER, FIND_DS, DATE_TIME, ISBN, MASACH};
